-- SELECT DATA FILES
SELECT * FROM DBA_DATA_FILES;

-- CREATE TABLESPACE
CREATE TABLESPACE BINGJJFLY

LOGGING

DATAFILE '/home/oraclehome/app/oradata/orcl/datafiles/BINGJJFLY.dbf'

SIZE 1000M

AUTOEXTEND ON

NEXT 1000M MAXSIZE 2000M

EXTENT MANAGEMENT LOCAL;

-- CREATE USER
CREATE USER BINGJJFLY IDENTIFIED BY BINGJJFLY123

DEFAULT TABLESPACE BINGJJFLY;

GRANT DBA TO BINGJJFLY;


-- GRANT AUTHORITY TO USER
GRANT

CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW ,CREATE ANY INDEX, CREATE ANY PROCEDURE,

ALTER ANY TABLE, ALTER ANY PROCEDURE,

DROP ANY TABLE, DROP ANY VIEW, DROP ANY INDEX, DROP ANY PROCEDURE,

SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE

TO BINGJJFLY;